### ISSUE TITLE
ts-node error

### ISSUE THREAD

**Issue by robross0606** [nareshbhatia/graphql-bookstore#6]
I followed the instructions in the blog to the letter but fail on the `2-queries-server` tag when running `yarn dev` due to the following error:
```
yarn run v1.17.3
$ nodemon --watch src -e ts,graphql --exec yarn start
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: ...\graphql-bookstore\apollo-bookstore-server\src/**/*
[nodemon] starting `yarn start`
$ ts-node src/index.ts
'ts-node' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[nodemon] app crashed - waiting for file changes before starting...
```
I see that `ts-node` is listed under `devDependencies` so I'm not sure what failed here.  Running `yarn` in the previous step seems to have not errored:
```
yarn install v1.17.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.37s.
```

**Comment by robross0606** [comment]
The problem is because I am running on Windows and commands appear to have both path issues and need `.cmd` postfix to be executed (`ts-node.cmd`).

**Comment by nareshbhatia** [comment]
Oh good! I was just trying to figure out what might be the issue.

I did this on a Mac, so Windows instructions might not be very bullet proof. Sorry!

**Comment by robross0606** [comment]
Spoke too soon.  This is still erroring for apparently other reasons:
```
yarn run v1.17.3
$ nodemon --watch src -e ts,graphql --exec yarn start
[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Code\learning\graphql\graphql-bookstore\apollo-bookstore-server\src/**/*
[nodemon] starting `yarn start`
$ ts-node.cmd src/index.ts
Error: Cannot find module 'core-js/proposals/array-flat-and-flat-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (...\graphql-bookstore\apollo-bookstore-server\node_modules\apollo-env\src\polyfills\array.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[nodemon] app crashed - waiting for file changes before starting...
```
